import type { SurveyQuestion } from "./types";

const yesNo = ["Sí", "No"];
const likert = ["1", "2", "3", "4", "5"];
const q = (
  number: number,
  section: number,
  text: string,
  type: SurveyQuestion["type"],
  options?: string[],
  detailWhen?: string[],
  detailLabel?: string,
): SurveyQuestion => ({
  id: `q${String(number).padStart(2, "0")}`,
  number,
  section,
  step: section <= 1 ? 0 : section <= 3 ? 1 : section <= 5 ? 2 : 3,
  text,
  type,
  options,
  detailWhen,
  detailLabel,
});

export const sectionTitles: Record<number, string> = {
  0: "Verificación inicial",
  1: "Caracterización básica",
  2: "Experiencia previa y relación con la programación",
  3: "Motivaciones para estudiar",
  4: "Dificultades, autoeficacia y emociones",
  5: "Hábitos de estudio y comportamientos de aprendizaje",
  6: "Preferencias y necesidades de apoyo",
  7: "Preguntas abiertas",
};

export const questions: SurveyQuestion[] = [
  q(
    1,
    0,
    "¿Estás cursando actualmente un curso introductorio de programación?",
    "single",
    yesNo,
  ),
  q(
    2,
    0,
    "¿Es tu primer año como estudiante en la Universidad de Costa Rica?",
    "single",
    yesNo,
  ),
  q(
    3,
    0,
    "¿Es la primera vez que llevas este curso de programación?",
    "single",
    ["Sí", "No, ya lo había cursado antes"],
  ),
  q(4, 1, "¿Cuál es tu edad?", "single", [
    "17 años o menos",
    "18 años",
    "19 años",
    "20 años",
    "21 años o más",
  ]),
  q(
    5,
    1,
    "¿Con cuál género te identificas?",
    "conditional",
    ["Mujer", "Hombre", "Prefiero no responder", "Otro"],
    ["Otro"],
    "Especificá tu respuesta",
  ),
  q(
    6,
    1,
    "Tipo de colegio de procedencia (el último en el que estudiaste antes de entrar a la UCR):",
    "conditional",
    ["Público académico", "Público técnico", "Privado", "Otro"],
    ["Otro"],
    "Indicá el tipo de colegio",
  ),
  q(
    7,
    1,
    "Durante el periodo lectivo, ¿dónde vivís principalmente?",
    "conditional",
    [
      "En la misma casa que mi familia",
      "En residencia estudiantil",
      "En un cuarto/alojamiento alquilado (solo o compartido)",
      "Otro",
    ],
    ["Otro"],
    "Indicá dónde vivís",
  ),
  q(8, 1, "¿Tenés alguna beca socioeconómica en la UCR?", "single", [
    "Sí",
    "No",
    "No sé / Prefiero no responder",
  ]),
  q(9, 1, "Además de estudiar, ¿actualmente trabajás?", "single", [
    "No trabajo",
    "Sí, trabajo menos de 20 horas a la semana",
    "Sí, trabajo 20 horas a la semana o más",
  ]),
  q(
    10,
    1,
    "¿Tenés otros compromisos frecuentes además del estudio (por ejemplo, asociaciones estudiantiles, voluntariado, deporte competitivo, cuidados familiares, etc.)?",
    "conditional",
    yesNo,
    ["Sí"],
    "Indicanos brevemente cuáles",
  ),
  q(
    11,
    1,
    "En el lugar donde vivís durante el semestre, ¿cómo describirías tu acceso a Internet?",
    "single",
    [
      "Muy bueno (estable y rápido)",
      "Bueno (generalmente funciona bien)",
      "Regular (a veces se cae o es lento)",
      "Malo (se cae con frecuencia o casi no tengo acceso)",
    ],
  ),
  q(
    12,
    1,
    "En ese mismo lugar, ¿tenés acceso a computadora para estudiar programación?",
    "single",
    [
      "Sí, tengo computadora propia",
      "Sí, comparto computadora con otras personas",
      "No tengo computadora, uso laboratorios u otros medios",
    ],
  ),
  q(
    13,
    2,
    "Antes de entrar a la UCR, ya había tenido contacto con la programación (por ejemplo, cursos, talleres, proyectos personales o del colegio).",
    "likert",
    likert,
  ),
  q(
    14,
    2,
    "En el colegio, sentía que me iba bien en matemáticas.",
    "likert",
    likert,
  ),
  q(
    15,
    2,
    "Antes de este curso, me sentía confiado(a) en mi capacidad para aprender programación.",
    "likert",
    likert,
  ),
  q(
    16,
    2,
    "Considero que, en comparación con mis compañeros(as), llegué al curso de programación con menos conocimientos previos sobre el tema.",
    "likert",
    likert,
  ),
  q(
    17,
    3,
    "Elegí esta carrera porque me interesa la tecnología y la programación.",
    "likert",
    likert,
  ),
  q(
    18,
    3,
    "Elegí esta carrera porque considero que ofrece buenas oportunidades laborales.",
    "likert",
    likert,
  ),
  q(
    19,
    3,
    "Entrar a la UCR representa una oportunidad importante de movilidad social para mí y mi familia.",
    "likert",
    likert,
  ),
  q(
    20,
    3,
    "Estoy satisfecho(a) con la carrera que estoy estudiando actualmente.",
    "likert",
    likert,
  ),
  q(
    21,
    3,
    "Me gustaría continuar en esta carrera hasta graduarme.",
    "likert",
    likert,
  ),
  q(
    22,
    4,
    "Cuando empiezo un nuevo ejercicio de programación, confío en que puedo encontrar una solución.",
    "likert",
    likert,
  ),
  q(
    23,
    4,
    "Cuando mi programa muestra errores que no entiendo, me frustro fácilmente.",
    "likert",
    likert,
  ),
  q(
    24,
    4,
    "Antes de los exámenes, pruebas cortas o exposiciones, me siento muy nervioso(a) o ansioso(a).",
    "likert",
    likert,
  ),
  q(
    25,
    4,
    "Siento que la nota que saque en este curso van a influir mucho en si sigo o no en la carrera.",
    "likert",
    likert,
  ),
  q(
    26,
    4,
    "A veces pienso que tal vez no soy “bueno(a) para esto” cuando algo no me sale a la primera.",
    "likert",
    likert,
  ),
  q(
    27,
    4,
    "Las responsabilidades fuera de la U (trabajo, familia, otros compromisos) hacen más difícil que pueda dedicar el tiempo que quisiera al curso de programación.",
    "likert",
    likert,
  ),
  q(
    28,
    4,
    "El lugar donde vivo (espacio, ruido, Internet, equipo) complica estudiar programación con tranquilidad.",
    "likert",
    likert,
  ),
  q(
    29,
    5,
    "Estudio programación de forma regular durante el semestre, no solo antes de los exámenes.",
    "likert",
    likert,
  ),
  q(
    30,
    5,
    "Paso tiempo practicando ejercicios de programación por mi cuenta, además de las tareas del curso.",
    "likert",
    likert,
  ),
  q(
    31,
    5,
    "Cuando no entiendo un tema, busco ayuda (compañeros, asistentes, profesor, foros u otros recursos).",
    "likert",
    likert,
  ),
  q(
    32,
    5,
    "Suelo asistir a las horas de consulta o espacios de apoyo cuando tengo dudas.",
    "likert",
    likert,
  ),
  q(
    33,
    5,
    "En clase, hago preguntas o participo cuando algo no me queda claro.",
    "likert",
    likert,
  ),
  q(
    34,
    5,
    "Me resulta difícil organizar mi tiempo entre cursos, tareas y actividades.",
    "likert",
    likert,
  ),
  q(
    35,
    6,
    "Me resulta más fácil aprender cuando veo ejemplos concretos de código y luego intento modificarlos.",
    "likert",
    likert,
  ),
  q(
    36,
    6,
    "Prefiero que me expliquen la solución paso a paso, en lugar de solo ver el código final.",
    "likert",
    likert,
  ),
  q(
    37,
    6,
    "Los videos o materiales interactivos me ayudan más que solo leer apuntes o libros.",
    "likert",
    likert,
  ),
  q(
    38,
    6,
    "Me gustaría tener una herramienta con la que pueda hacer preguntas sobre programación en cualquier momento (por ejemplo, un agente conversacional o asistente virtual).",
    "likert",
    likert,
  ),
  q(
    39,
    6,
    "Agradecería que esa herramienta me ayude a organizar el estudio del curso (por ejemplo, sugerir por dónde empezar, cómo dividir ejercicios o cómo planear el tiempo).",
    "likert",
    likert,
  ),
  q(
    40,
    6,
    "Sería útil que la herramienta tuviera en cuenta que a veces tengo problemas de tiempo, Internet o equipo para estudiar.",
    "likert",
    likert,
  ),
  q(
    41,
    7,
    "En tus palabras, ¿qué es lo que más se te dificulta actualmente en el curso de programación?",
    "open",
  ),
  q(
    42,
    7,
    "¿Qué aspectos del contexto (lugar donde vivís, trabajo, familia, otros cursos, salud, etc.) sentís que más influyen en tu desempeño en programación?",
    "open",
  ),
  q(
    43,
    7,
    "Imaginá una herramienta que te acompañe mientras aprendés programación (por ejemplo, un agente conversacional). ¿Qué características tendría para que realmente te sea útil?",
    "open",
  ),
  q(
    44,
    7,
    "Si tuvieras que describir brevemente a un(a) estudiante “típico(a)” de tu grupo en el curso de programación, ¿cómo lo describirías? (pensando en contexto, hábitos, motivaciones, dificultades).",
    "open",
  ),
];

export const characterizationQuestions = questions.filter(
  (question) => question.section <= 1,
);
